### ISSUE TITLE
add a new end point

### ISSUE THREAD

**Issue by ssat4805** [sabesansathananthan/github-linguist-json#3]
endpoint  `/lang`
add a new endpoint that gives the language and respective color details. 
expect JSON format
``` JSON
{
"JavaScript" : "f1e05a" ,
"PureScript": "#1D222D",
}
```

**Comment by itsnitinr** [comment]
I'd like to help.

**Comment by ssat4805** [comment]
sure I will assign you.  Don't forget to give a star to this repo.

**Comment by itsnitinr** [comment]
The response should be like this right?
```JSON
{
    "1C Enterprise": "#814CCC",
    "ABAP": "#E8274B",
}
```
For all languages having color property.

**Comment by ssat4805** [comment]
yes extractly ...  but we already save the YAML file locally and convert it as JSON. That Yaml file will update every month.
